### ISSUE TITLE
Error when trying to login in with Google

### ISSUE THREAD

**Issue by jensaja** [AxaGuilDEv/react-oidc#758] opened 2022-04-22 10:24 UTC
### Issue and Steps to Reproduce

Create a [Google OIDC client](https://developers.google.com/identity/protocols/oauth2/openid-connect) and try to use it with this library:

```
import {Provider} from "react-redux";
import {OidcProvider} from "@axa-fr/react-oidc-context";

const oidcConfig = {
	client_id: 'your_google_client_id',
	redirect_uri: `${location.protocol}//${location.host}/`,
	scope: 'openid',
	authority: 'https://accounts.google.com',
	service_worker_only: false
};

const root = createRoot(document.getElementById('root'));
root.render(
	<Provider store={store}>
		<OidcProvider configuration={oidcConfig}>
			<App/>
		</OidcProvider>
	</Provider>
);
```
### Versions

Tried in version 5.3.1

#### Expected

Redirect to Google SSO

#### Actual

Before the actual redirect, the following error occurs because sessionStorage is empty:
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.loadItemsAsync (initSession.ts:9:1)
    at Oidc.<anonymous> (oidc.ts:419:1)
    at step (noHashQueryStringUtils.ts:3:1)
    at Object.next (noHashQueryStringUtils.ts:3:1)
    at fulfilled (noHashQueryStringUtils.ts:3:1
```

### Additional Details

I use React-Saga within my React application

**Comment by guillaume-chervet** [comment] 2022-04-22 13:22
Hi @jensaja ,

Thank you very much for your PullRequest!
I cannot reproduce the error with other providers.
I may need more details.

Can you try to add "openid profile email" instead of just "openid"?

You callback route seems to redirect to base path route.
Do you have a full callback route like :
redirect_uri: `${window.location.origin}/callback`
?

Regards,

Guillaume

**Comment by jensaja** [comment] 2022-04-22 15:04
Hi @guillaume-chervet,

The issue was indeed that my redirect_uri was missing a /callback route in the path. So this had nothing to do with Google OAuth.

Another issue that was Google-specific (leaving this for future implementers), is that Google only allows an implicit flow if you don't pass a client secret. If you want to perform a code grant flow with PKCE, you need to pass a client secret in your token request. In this library, this can be done by passing it as `token_request_extras` in the config:

```
const oidcConfig = {
	client_id: 'your_google_client_id',
	redirect_uri: `${location.protocol}//${location.host}/callback/`,
	scope: 'openid',
	authority: 'https://accounts.google.com',
	service_worker_only: false,
	token_request_extras: {'client_secret': 'your_google_client_secret'}
};
```

Regards

**Comment by guillaume-chervet** [comment] 2022-04-22 15:07
Thank you for your feedback @jensaja .

Here a full config google example. https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/context/src/configurations.ts

You may consider to use serviceworker in order to increase a lot the security. Have fun !

**Comment by jensaja** [comment] 2022-04-24 12:45
Thank you so much @guillaume-chervet . I wish I found the example earlier :)

One more issue though: the token request succeeds. But when trying to parse the response, the [extractAccessTokenPayload](https://github.com/AxaGuilDEv/react-oidc/blob/b7e36dfe5e3a29f7adb2b7fb500e6b4482a83c32/packages/context/src/oidc/vanilla/oidc.ts#L47) method fails when trying to perform an atob operation on the returned token. The following exception occurs:
```
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```
Is this a known issue? The access token returned by Google looks like this: `ya29.A0ARrd...`

**Comment by guillaume-chervet** [comment] 2022-04-24 13:32
Hi @jensaja, thank you again for the feedback.

The behavior is the one expected.
I may replace the console.error by console.warn and i may add a better check before trying to parse the token in order to avoid using an ugly exception.

**Comment by guillaume-chervet** [comment] 2022-04-24 14:13
It was quick to do. It work with my google auth. Doe it work for you with the last version?

**Comment by jensaja** [comment] 2022-04-25 16:42
Thank you so much! It works with Google with just a warning. One comment though: https://github.com/AxaGuilDEv/react-oidc/commit/cb946a94975cf11076b0b8b428bdee61c2d6ff78#r72099437

**Comment by guillaume-chervet** [comment] 2022-04-28 21:16
I close the issue  @jensaja , thank you and feel free to reopen it if you need it !

**Closed by guillaume-chervet** 2022-04-28 21:16 UTC

**Comment by timwsuqld** [comment] 2022-10-18 03:11
Hey guys
So Google returns the JTW in the `id_token` not in `access_token`, are we able to modify this library so we can detect that and return the JWT from `id_token` when it's Google?

**Comment by guillaume-chervet** [comment] 2022-10-18 03:17
Hi @timwsuqld , the library return already the id_token. What is exacty you need?

**Comment by timwsuqld** [comment] 2022-10-18 04:01
@guillaume-chervet thanks, I've worked out that we just need to use `useOidcIdToken` instead of `useOidcAccessToken` when using Google for OIDC. Hopefully this comment helps someone else stumbling across this issue.

**Comment by guillaume-chervet** [comment] 2022-10-18 05:43
Thank you @timwsuqld  :)
