### ISSUE TITLE
Support for vitejs

### ISSUE THREAD

**Issue by radu-cs** [AxaGuilDEv/react-oidc#671] opened 2021-11-03 15:44 UTC
### Not possible to use with https://github.com/vitejs/vite

I started a new project following vitejs documentation:

`npm init vite@latest my-react-app -- --template react`

I added all the necessary packages and configurations for @axa-fr/react-oidc-context
When I try to import anything from @axa-fr/react-oidc-context vitejs dev server does not start with the following Error:

> [plugin: vite:dep-scan] Failed to resolve entry for package "@axa-fr/react-oidc-context". The package may have incorrect main/module/exports specified in its package.json

Hopefully it is an easy fix. Thank you in advance.

### Versions

3.1.7

### Screenshots

`none`

#### Expected

To work :)

#### Actual

It does not work

### Additional Details

- Installed packages:
```
"dependencies": {
    "@axa-fr/react-oidc-context": "^3.1.7",
    "bootstrap": "^5.1.3",
    "bootstrap-icons": "^1.7.0",
    "dayjs": "^1.10.7",
    "oidc-client": "^1.11.5",
    "react": "^17.0.2",
    "react-bootstrap": "^2.0.1",
    "react-dom": "^17.0.2",
    "react-router-dom": "^5.3.0",
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^1.0.7",
    "vite": "^2.6.13",
    "vite-plugin-svgr": "^0.4.0"
  }
```

- vite.config.js file content:

``` js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import svgrPlugin from 'vite-plugin-svgr'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    svgrPlugin()
  ]
})
```

**Comment by guillaume-chervet** [comment] 2021-11-03 20:50
@samuel-gomez-axa are you interrested to look at this?

**Comment by honzahruby** [comment] 2021-11-15 12:24
I managed to get it working by adding this to the vite config
```typescript
resolve: {
  mainFields: ['module', 'main', 'jsnext:main', 'jsnext'],
},
```

**Comment by radu-cs** [comment] 2021-11-15 12:47
> 
> 
> I managed to get it working by adding this to the vite config
> 
> ```ts
> resolve: {
>   mainFields: ['module', 'main', 'jsnext:main', 'jsnext'],
> },
> ```

I can confirm that it is working.
I'll let the maintainers decide if this should be the accepted solution and close the issue.

Thank you very much @honzahruby .

**Comment by rickyoleary** [comment] 2022-01-07 09:38
Were the above issues resolved @radu-cs?

**Comment by radu-cs** [comment] 2022-01-07 11:12
> Were the above issues resolved @radu-cs?

Unfortunately no.

**Comment by guillaume-chervet** [comment] 2022-01-07 19:13
I am not sure to understand because i do not know vite. Do we need to do something inside react-oidc repository?

**Comment by radu-cs** [comment] 2022-01-08 09:46
I don't know exactly what should be done to make it work with vite.
Maybe this article could shed some light on the issue:
https://patak.dev/vite/ecosystem.html

**Comment by honzahruby** [comment] 2022-01-08 10:10
The problem is that vite by default picks up `jsnext:main` - the uncompiled `src` folder but it cannot process it. You can either point `jsnext:main` to the pre-compiled `dist` folder or add a `module` field pointing to the `dist` folder. That should be a non-breaking change anyway.

In the workaround provided above, you can see I changed the vite resolution order to pick up `main` before `jsnext:main`.

**Comment by guillaume-chervet** [comment] 2022-02-02 13:27
A v4 version will come soon with that modification

**Comment by radu-cs** [comment] 2022-02-02 15:13
> A v4 version will come soon with that modification

Good News! 👍 
Thank you!

**Comment by radu-cs** [comment] 2022-02-08 19:16
> I have made the change in the comming v4.
> 
> Have you the possibilityu to try? https://www.npmjs.com/package/@axa-fr/react-oidc-context
> 
> there are some breaking change, but it simplify and fix all the main problems

Hey there,
I will try it in the next days and I'll let you know.
Thank you once again.

**Comment by radu-cs** [comment] 2022-02-09 10:04
Hey @guillaume-chervet ,

I tried the new alpha.

**The good news is that vite loads the package without problems.**

The not so good news is the need of refactoring to overcome the breaking changes.

Unfortunately I don't have the time now for refactoring but I'll let you know when I'll get to it and how it goes.

_**Bottom line is that vite is not crashing when the project starts. 👍**_ 
Feel free to close this if you consider that the not crashing vite is enough to consider that vite support is working.

Thank you!

**Comment by guillaume-chervet** [comment] 2022-02-21 16:54
The new version V4 doesn't really use context inside (I will remove dependency to it).
It is may be already compatible with redux.

**Comment by radu-cs** [comment] 2022-02-22 08:07
> The new version V4 doesn't really use context inside (I will remove dependency to it). It is may be already compatible with redux.

Hello Guilaume,

That is unfortunate for our use case since we started the project specifically not choosing Redux as state management library.
I hope there would be a work around to still use the Context API or the old versions would be still supported.

Thank you for your work!

**Comment by guillaume-chervet** [comment] 2022-02-22 08:11
V4 is compatible react and context api, but does not need it.

**Comment by radu-cs** [comment] 2022-02-22 08:19
That is good to hear. 😃 
Please feel free to close this issue if you think it is appropriate.

**Comment by guillaume-chervet** [comment] 2022-02-22 09:58
Thank you I close the issue.

**Closed by guillaume-chervet** 2022-02-22 09:58 UTC
