### ISSUE TITLE
Provide documentation on how to use fetch-observable

### ISSUE THREAD

**Issue by jkhaui** [AxaGuilDEv/react-oidc#568] opened 2020-12-20 00:24 UTC
I'm most interested in using `react-oidc-fetch-observable` as I'm already using rxjs in my project. However, I've no idea how to utilise it as there's no README and none of the main components appear to be exported from the package. Some documentation on how to use it would be great. I don't mind contributing if I can figure out how to get it working myself.

**Comment by guillaume-chervet** [comment] 2021-02-26 08:49
@thiesbarry, are you able to give some information or sample of code about it? A readme would be awesome

**Comment by linwilai918** [comment] 2021-08-06 16:45
[rxjs](https://github.com/AxaGuilDEv/react-oidc/issues/568#issue-771482746) 
Duplicate of # @tlaukkanen

**Comment by guillaume-chervet** [comment] 2022-04-18 19:44
Hi guys, i close the pull request i v5 we have choose to not integrate the HOC inside the library to simplify it. Thank you very much!

**Closed by guillaume-chervet** 2022-04-18 19:44 UTC
Labels: help wanted, documentation
