### ISSUE TITLE
Storage object could not be cloned.

### ISSUE THREAD

**Issue by Zhuohui-Li** [AxaGuilDEv/react-oidc#911] opened 2022-11-28 17:30 UTC
### Issue and Steps to Reproduce

copy the ServiceWorker.js from `oidc/vanilla/OidcServiceWorker.js` to `./public` and then run
```
index.js:1 DOMException: Failed to execute 'postMessage' on 'ServiceWorker': Storage object could not be cloned.
    at http://localhost:3000/static/js/vendors~main.chunk.js:505176:27
    at new Promise (<anonymous>)
    at http://localhost:3000/static/js/vendors~main.chunk.js:505165:12
    at _callee3$ (http://localhost:3000/static/js/vendors~main.chunk.js:505363:62)
    at tryCatch (http://localhost:3000/static/js/vendors~main.chunk.js:527455:17)
    at Generator.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:527536:22)
    at Generator.next (http://localhost:3000/static/js/vendors~main.chunk.js:527480:21)
    at http://localhost:3000/static/js/vendors~main.chunk.js:504934:67
    at new Promise (<anonymous>)
    at push.../../node_modules/@axa-fr/react-oidc/dist/vanilla/initWorker.js.__awaiter (http://localhost:3000/static/js/vendors~main.chunk.js:504913:10)
    at Object.initAsync (http://localhost:3000/static/js/vendors~main.chunk.js:505356:22)
    at Oidc._callee14$ (http://localhost:3000/static/js/vendors~main.chunk.js:506711:50)
    at tryCatch (http://localhost:3000/static/js/vendors~main.chunk.js:527455:17)
    at Generator.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:527536:22)
    at Generator.next (http://localhost:3000/static/js/vendors~main.chunk.js:527480:21)
    at fulfilled (http://localhost:3000/static/js/vendors~main.chunk.js:505682:24)
```

### Versions
6.10.20
### Screenshots
![image](https://user-images.githubusercontent.com/108833137/204342248-8d1b2a75-b316-43bf-badc-87af8fd48c71.png)

#### Expected
no errors
#### Actual
throwing a DOMException error
### Additional Details

- Installed packages:
React

**Comment by guillaume-chervet** [comment] 2022-11-28 19:23
Hi @Zhuohui-Li , thank you for your issue.
What does look like your configuration?

**Comment by guillaume-chervet** [comment] 2022-11-28 19:25
I think the issue is Linked to https://github.com/AxaGuilDEv/react-oidc/issues/910

You may temporary comment storage mode. I will try to fix it tomorrow.

**Comment by Zhuohui-Li** [comment] 2022-11-28 19:33
Hi @guillaume-chervet 
The configuration is 
```
client_id: 
    redirect_uri:
    scope: 
    authority: 
    refresh_time_before_tokens_expiration_in_second: 10,
    service_worker_relative_url: `/OidcServiceWorker.js`,
    service_worker_only: false, 
    storage: localStorage,
    authority_configuration: {
   
    },
  },
```

**Comment by guillaume-chervet** [comment] 2022-11-28 19:36
Thank you @Zhuohui-Li , you need to comment storage line in your configuration.
If it does not work you can downgrade to an previous version.
I will fix this tomorrow.  Very sorry for that bug @Zhuohui-Li

**Comment by guillaume-chervet** [comment] 2022-11-28 20:02
Which browser are you using? @Zhuohui-Li

**Comment by Zhuohui-Li** [comment] 2022-11-28 20:10
> Which browser are you using? @Zhuohui-Li

Chrome Version 107.0.5304.121 on M1 MacBook

**Comment by guillaume-chervet** [comment] 2022-11-29 20:00
hi @Zhuohui-Li ,

Version 6.10.21 fix this issue: https://github.com/AxaGuilDEv/react-oidc/commit/1b1cfd58b6dd88968e68175e20435854b34acba1 
I'am very sorry for the delay, thank you very much for your help :)

**Comment by guillaume-chervet** [comment] 2022-12-03 13:27
Hi @Zhuohui-Li , i think the error is fixed now. May we close the issue?

**Closed** 2022-12-04 04:59 UTC

**Comment by Zhuohui-Li** [comment] 2022-12-04 05:27
Hi @guillaume-chervet Thanks a lot. I closed the issue
