### ISSUE TITLE
Problem with react-router-dom v6?

### ISSUE THREAD

**Issue by furdzik** [AxaGuilDEv/react-oidc#827] opened 2022-07-26 10:44 UTC
### Issue and Steps to Reproduce

I have a code, like this:

App.jsx:
```jsx
import { OidcProvider } from '@axa-fr/react-oidc';

<OidcProvider configuration={oidcConfiguration}>
  // ...
  <RoutesConfig />
  //  ...
</OidcProvider>
```

RoutesConfig.jsx
```jsx
<BrowserRouter basename="/somebase">
  <Routes>
    <Route
      path="/"
      element={(
        <OidcSecure>
          <MyComponent />
         </OidcSecure>
      )}
    />
  </Routes>
</BrowserRouter>
```

**I got an error.** 

```
TypeError: Cannot read properties of null (reading 'hasChildNodes')
```

**It is still doing what needs to be done, but my app crashes before redirect.   
Fothermore when login is successful, It returns with no error**
I don't want the app to crash before redirect.

When I don't have OidcSecure wrapped, and click login() funcion on some button I don't gent this error.  
(But of course I need to be automatic).

```jsx
const { login, logout, isAuthenticated } = useOidc();

// ...

<button onClick={() => login()}>login</button>
```

If I try to do login automatic i got the same error. Exacly like with `OidcSecure`.
I have tried to use `withOidcSecure`, but in new reacr-router-dom it's needed to return a component like: `<Component />` not as a function.

```jsx
  import { useOidc } from '@axa-fr/react-oidc';

  // ...

  const { login, logout, isAuthenticated } = useOidc();
  login();
  // ...
```

It could be something with `react-router-dom` in 6.3.0 version? Or maybe my use case is wrong?

### Versions

- @axa-fr/react-oidc: 6.0.0-beta10

### Screenshots

![image](https://user-images.githubusercontent.com/7780054/180983138-233f7afe-db6f-494c-bcd2-a50b5a84cdc6.png)

#### Expected

No error

#### Actual

Error as on screen

### Additional Details

- Installed packages:
   - react: 18.2.0
   - react-router-dom: 6.3.0

**Comment by guillaume-chervet** [comment] 2022-07-27 09:37
Hi @furdzik ,

Thank you very much for your issue.

I cannot reproduce the error with beta 13 and :
- react: 18.2.0
- react-router-dom: 6.3.0
https://black-rock-0dc6b0d03-817.westeurope.1.azurestaticapps.net/profile-secure-component

Do you have a sample of code on git or something else where I can reproduce the error quickly ?

**Comment by furdzik** [comment] 2022-07-27 12:55
Hi @guillaume-chervet,

Thank you for quick replay.

After your info, I had checked the whole app, and it was a problem not connected with my previous assumptions (redirect cased code from other package to break because it couldn't find a div with needed ref).

So sorry I didn't think of this sooner!

I am so sorry for the hassle 🙏

**Comment by guillaume-chervet** [comment] 2022-07-27 15:16
Thank you for using reatc oidc @furdzik ,
I hope it will help you.
Yes please, feel free to close the issue :)

**Closed** 2022-07-28 06:26 UTC
