### ISSUE TITLE
authentication/callback not redirecting to the home page

### ISSUE THREAD

**Issue by frogerdevs** [AxaGuilDEv/react-oidc#793] opened 2022-06-06 13:26 UTC
### Issue and Steps to Reproduce
Hi, @guillaume-chervet 
I found the issue when trying to log in and not redirecting to the home page.

Here is my configuration:
**Client (using react)** running on : **http://localhost:4200/**
**Identity Server (using openiddict)** running on : **https://localhost:7141/**
-> I'm trying to register the **wrong Application** : http://localhost:4201/ (Wrong port)

when trying to log in,  I got an error like this
![image](https://user-images.githubusercontent.com/38326221/172166794-21ae1f93-043f-4bb8-a836-6820021dfb07.png)

when I Fix the registered Application in my **Identity Server** -> change it to **http://localhost:4200/**
success shows login form (only refresh the browser), but after login, it won't go to redirect Url, stuck like this image:
![image](https://user-images.githubusercontent.com/38326221/172165224-26f39b0c-9c15-40c3-ab82-fda7821711d1.png)

### Versions
  "dependencies": {
    "@axa-fr/react-oidc": "^5.10.0",
}

Can you give me a suggestion?
I have tried your sample in this repo, but the result still same.

but if the configuration is valid from the start, the issue not happened.

Thank you for your great work.

**Comment by frogerdevs** [comment] 2022-06-06 16:40
Hi, @guillaume-chervet thanks for your reply,

- Yes, it works great when the configuration is valid from the beginning.
- Here's the capture I got when it's stuck
![image](https://user-images.githubusercontent.com/38326221/172205112-ca164629-828e-4beb-a2db-7e9185e06d31.png)

does it help?

Thanks

**Comment by guillaume-chervet** [comment] 2022-06-08 23:09
Does the version 5.10.1 fix your issue?
It is a bug quite hard to debug ^^

**Comment by frogerdevs** [comment] 2022-06-09 05:23
hi @guillaume-chervet,

I have already updated to version 5.10.1, and still have the same problem.

**Comment by guillaume-chervet** [comment] 2022-06-09 05:50
Thank you for the feedback @frogerdevs . I will make some tests again today.

**Comment by frogerdevs** [comment] 2022-06-09 06:30
Thanks for keeping me updated. I hope it will fix soon. 
God bless you.

**Comment by khyapate** [comment] 2022-06-14 17:17
@guillaume-chervet Thanks for looking into this. Just checking, is this issue fixed, if yes in which version?

**Comment by khyapate** [comment] 2022-06-14 18:47
Thanks @guillaume-chervet  for your quick response.

**Comment by guillaume-chervet** [comment] 2022-06-20 06:57
I pushed a fixed yestaday. I suspect 2 things, so i make a first try. It hard to reproduce debug.

**Comment by guillaume-chervet** [comment] 2022-06-20 06:57
I will test a lot that fix today.

**Comment by khyapate** [comment] 2022-06-20 17:12
Thanks @guillaume-chervet for the updates.

**Comment by guillaume-chervet** [comment] 2022-06-21 06:35
I do not know why but the request token sometime is stuck and never respond.
The timeout security i have added work but it fall as an error.
The problem is that it seems imposible to reproduce it in debug mode. I really need to fix it.

**Comment by guillaume-chervet** [comment] 2022-06-27 18:26
Hi @JProbe ,

Your redirect_uri must be an uri not usés by you application.
For exemple :
https://localhost:8000/appName/oidc-callback

**Comment by drod21** [comment] 2022-08-18 21:14
I'm having a similar issue, but i get stuck on the /callback page, and see this message in the console:
Delivering authorization response

it doesn't move from here. It logs the users token, etc.. 
I'm trying to implement something to similar to signinRedirectCallback, is this possible with this library? Should I open a new issue for discussion?

**Comment by JProbe** [comment] 2022-08-18 22:43
> Hi @JProbe , did you try hash redirect? Did you solve ypur problem?

Hello @guillaume-chervet it hasn't worked for us.Our Identity provider doesn't support "iss" parameter and library seem to expect iss or issuer parameter after authorization call.We had to move to other library owing to time constraints.

**Comment by guillaume-chervet** [comment] 2022-08-19 06:13
Hi @JProbe , @drod21 what are your oidc provider name in order to make some test? Appauthjs used in  background seems compatible with all oidc provider. If not, we can request update or build one.

**Comment by drod21** [comment] 2022-08-19 09:46
@guillaume-chervet we use IdentityServer 4. 

Any idea on how to debug why/where it’s “stuck”? I’m assuming it might be a configuration issue, but just not sure?

**Comment by guillaume-chervet** [comment] 2022-08-19 12:03
Hi @drod21 , may you put your oidc configuration here?
Identity server 4 must work with react oidc. I will test on the next monday.
Did you git clone the demo and remplace the configuration by yours?

**Comment by drod21** [comment] 2022-08-19 12:50
Yep! @guillaume-chervet  here you go:

`
const url = `${window.location.protocol}//${window.location.hostname}${
	window.location.port ? `:${window.location.port}` : ''
}`

export const oidcSettings: OidcConfiguration = {
	authority: authUrl,
	authority_configuration: {
		authorization_endpoint: `${authUrl}/connect/authorize`,
		check_session_iframe: `${authUrl}/connect/checksession`,
		end_session_endpoint: `${authUrl}/connect/endsession`,
		revocation_endpoint: `${authUrl}/connect/revocation`,
		token_endpoint: `${authUrl}/connect/token`,
		userinfo_endpoint: `${authUrl}/connect/userinfo`,
	},
	client_id: process.env.REACT_APP_CLIENT_ID ?? '',
	extras: { acr_values: 'tenant:xxxx', issuer: authUrl },
	redirect_uri: `${url}/callback`,
	scope: 'openid *_api profile offline_access', // *_api is placeholder for our api scopes, excluding for post purposes
	silent_redirect_uri: `${url}/callback`,
	token_request_timeout: 60000,
}`

I'll give cloning the demo a try and replacing with my config.

**Comment by guillaume-chervet** [comment] 2022-08-19 12:55
Thank you @drod21 , you cannot use the same callback uri for silent signin in v6. It may be the problem. What happen if you comment silent login uri for a test purpose.

**Comment by drod21** [comment] 2022-08-19 12:58
sunuva - that worked! thanks. I'll create a new issue if i run into other issues.

Appreciate the help!

**Comment by guillaume-chervet** [comment] 2022-08-19 12:58
You may also remove authority_configuration. It should work with identity server 4.

**Comment by guillaume-chervet** [comment] 2023-02-05 07:04
Hi @frogerdevs , thank you for the issue.
I close it because i think it all rigth now. Feel free to reopen it if you need it.

**Closed by guillaume-chervet** 2023-02-05 07:04 UTC
