### ISSUE TITLE
undefined is not valid JSON

### ISSUE THREAD

**Issue by beanovar** [AxaGuilDEv/react-oidc#871] opened 2022-09-27 09:06 UTC
Hi - I'm sorry at this point I'm not sure what it takes to reproduce, will post if I find out. 
However sometimes the page errors out with the following logs in the console: 

```
SyntaxError: "undefined" is not valid JSON
   at JSON.parse (<anonymous>)
   at getLoginParams (oidc.ts:199:1)
   at Oidc._callee23$ (oidc.ts:963:1)
   ....
   at localsilentLoginAsync (oidc.ts:961:1)
refreshTokensAsync_silent_error {"message":"exceptionSilent","exception":"\"undefined\" is not valid JSON"}
```

Do you know what would cause this at all? 

Thankyou

**Comment by guillaume-chervet** [comment] 2022-09-27 11:10
Hi @beanovar thank you very much for your issue.

Do you have a sample of your configuration?
Does it occur quickly or after a big amount of time?
Does it occur often?

**Comment by beanovar** [comment] 2022-09-27 16:13
Hi - I might see it every 3 or so days? Only after a big amount of time, maybe while the page is in the background. Haven't seen the pattern yet, or how to reproduce. 

Our config sets 
- client_id
- redirect_uri
- silent_redirect_uri
- silent_login_uri
- scope including offline_access
- authority
- authority_time_cache_wellknowurl_in_second
- refresh_time_before_tokens_expiration_in_second
- service_worker_relative_url
- service_worker_only -> true
- monitor_session -> false

I will let you know if I see what can re-produce it.
Thanks

**Comment by guillaume-chervet** [comment] 2022-09-29 18:14
Thank you @beanovar, on which browser do you have this error?

**Comment by beanovar** [comment] 2022-10-02 09:27
Chrome - I'm going to close this for now as I have not seen it for a while and think it was to something to do with the authentication server returning bad responses. It might be helpful to review what the lib might do if the auth server returns unexpected results or errors? It could be something else entirely though, just guessing. Thanks!

**Comment by guillaume-chervet** [comment] 2022-10-02 11:40
Thank you @beanovar , i think it migth have something link with session livecycle. If you have the problem back you can reopen the issue.

**Comment by beanovar** [comment] 2022-10-09 19:32
I found out how to reproduce this ! 
1) Have two tabs open, one in the foreground, one in the background (hidden)
2) Ensure the auth server is down / returns an error response when the visible tab refreshes it's token.
3) Let it retry the 4 times before eventually failing. 
4) Now make the second tab visible, and you will see the "undefined" is not valid JSON in that tab's console.

Ideally, I would like all tabs to recover automatically once the auth sever has recovered... maybe they could continue trying rather than give up after 4 attempts?

Thanks!

**Comment by guillaume-chervet** [comment] 2022-10-09 20:56
Thank you very much for this ! 

I will fix it as soon as possible. Yes may be retry whithout limit in certain situation may work for this issue.

**Comment by guillaume-chervet** [comment] 2023-01-12 20:49
Thank you @alex-airbox for the feedback.
Very sorry I just fix it. Version 6.13.2 work with localStorage.

**Comment by alex-airbox** [comment] 2023-01-16 08:44
Apologies for not sending feedback last week, I went back to an old version as I had issues with the log out. After a `auth.logout('/');` it'd successfully log me out but I won't be able to log in again, I think issue was _undefined tokens_ this time. Solved going back to 6.6.7.

**Comment by Zhuohui-Li** [comment] 2023-01-17 14:36
Hi @guillaume-chervet 
in version 6.13.3 I got
```
oidc.ts:223 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'refreshToken')
    at _callee5$ (oidc.ts:223:1)
    at tryCatch (regeneratorRuntime.js:86:1)
    at Generator._invoke (regeneratorRuntime.js:66:1)
    at Generator.next (regeneratorRuntime.js:117:1)
    at fulfilled (noHashQueryStringUtils.ts:11:1)
```

**Comment by guillaume-chervet** [comment] 2023-01-19 19:21
Thank you @alex-airbox for the feedback :)

**Comment by guillaume-chervet** [comment] 2023-01-19 19:22
@Zhuohui-Li what does look like your configuration ?  I cannot reproduce it.

**Comment by guillaume-chervet** [comment] 2023-02-05 06:39
Hi close this issue. I think it is resolved. Feel free to reopen it if you need.

**Closed by guillaume-chervet** 2023-02-05 06:39 UTC
